"use client";

import jsPDF from "jspdf";

export default function ForensicReports() {

  const generatePDF = () => {

    const doc = new jsPDF();

    doc.setFontSize(22);

    doc.text(
      "AGI FORENSIC REPORT",
      20,
      20
    );

    doc.setFontSize(12);

    doc.text(
      "Advanced Blockchain Intelligence",
      20,
      35
    );

    doc.text(
      "Case ID: AGI-2026-4421",
      20,
      50
    );

    doc.text(
      "Risk Level: HIGH",
      20,
      60
    );

    doc.text(
      "AML Status: Suspicious Activity Detected",
      20,
      70
    );

    doc.text(
      "Blockchain Analysis Summary:",
      20,
      90
    );

    doc.text(
      "- Cross-chain movement identified",
      25,
      105
    );

    doc.text(
      "- Mixer interaction detected",
      25,
      115
    );

    doc.text(
      "- Behavioral anomaly confirmed",
      25,
      125
    );

    doc.text(
      "- AI risk correlation completed",
      25,
      135
    );

    doc.text(
      "Generated by AGI Intelligence Engine",
      20,
      170
    );

    doc.save(
      "AGI_Forensic_Report.pdf"
    );

  };

  return (

    <div>

      <h1 className="text-5xl font-black text-cyan-300">

        FORENSIC REPORTS

      </h1>

      <p className="mt-4 text-gray-400">

        Executive forensic intelligence reports

      </p>

      <div className="mt-10 rounded-xl border border-cyan-400/20 bg-black/40 p-10">

        <h2 className="text-2xl font-bold text-white">

          Generate Institutional Report

        </h2>

        <p className="mt-4 text-gray-400">

          Export blockchain forensic investigation summary.

        </p>

        <button
          onClick={generatePDF}
          className="mt-8 rounded-lg bg-cyan-500 px-8 py-4 font-bold text-black transition-all hover:bg-cyan-400"
        >

          GENERATE PDF REPORT

        </button>

      </div>

    </div>

  );

}

